const esbuild = require("esbuild");
const fs = require("fs");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const isProd = process.argv[2] === "production";

// Define settings
const buildOptions = {
	banner: { js: banner },
	entryPoints: ["src/main.ts", "src/styles/main.css"],
	bundle: true,
	external: ["obsidian", "electron"],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: isProd ? false : "inline",
	treeShaking: true,
	outdir: "dist",
	loader: {
		".svg": "text",
	},
};

// Post-build cleanup function
const postBuild = () => {
	if (fs.existsSync("manifest.json")) {
		fs.copyFileSync("manifest.json", "dist/manifest.json");
	}

	// Check for the nested CSS file esbuild generated
	const nestedCSS = "dist/styles/main.css";
	const rootStyles = "dist/styles.css";

	if (fs.existsSync(nestedCSS)) {
		fs.renameSync(nestedCSS, rootStyles);

		// Clean up the now-empty dist/styles directory if you want
		const nestedDir = "dist/styles";
		if (fs.readdirSync(nestedDir).length === 0) {
			fs.rmdirSync(nestedDir);
		}
	} else if (fs.existsSync("dist/main.css")) {
		// Fallback in case esbuild puts it in the root (depends on version/OS)
		fs.renameSync("dist/main.css", rootStyles);
	}

	console.log(`Build finished at ${new Date().toLocaleTimeString()}`);
};

async function run() {
	if (isProd) {
		// Production: Just build once
		try {
			await esbuild.build(buildOptions);
			postBuild();
			process.exit(0);
		} catch (e) {
			console.error(e);
			process.exit(1);
		}
	} else {
		// Development: Create context and watch
		try {
			const ctx = await esbuild.context({
				...buildOptions,
				plugins: [{
					name: 'post-build-plugin',
					setup(build) {
						build.onEnd(postBuild);
					},
				}],
			});
			await ctx.watch();
			console.log("Watching for changes...");
		} catch (e) {
			console.error(e);
			process.exit(1);
		}
	}
}

run();